# What is Numpy ?
### Array in general refers to a named group of homogeneous elements.
### It is a module in Python language 
### This module is used in **Data manipulation** and machine learning tasks i.e. **Scientific computing tasks**.
### Numpy Array is simply a **grid** that contains values of **same type**.

# Why Numpy ?
### _**Provides efficient storage**_ : It means creating a list or other data type which contain group of elements consume lot of memory of our system but NumPy is one of the best option for programmers to use storage efficiently as it saves lot of memory of our system.
### It also provides _**better ways of handling data for processing**_. : It means NumPy arrays provide better ways or methods to handle data i.e. while using NumPy arrays the programmer has **full control over data** means he/she can handle each and every data of NumPy array.
### It is fast and easy to learn.

# What is Jupyter ?
### _**Jupter notebook is an open source web application that allows you to create and share documents that contain live code, visualization and narrative text.**_
### Notebook has support for over 40 programming languages including Python, R etc.
### Notebooks can be shared with other using email, Dropbox, Github and Jupyter Notebook Viewer.
### Your code can even produce rich, interactive output.

# Jupyter Overview
### Jupyter allow user to create notebooks.
### When you import numpy as np, it describes that you have imported NumPy module in your python program with the alias or new name ‘np’. 
### You can give any variable name instead of np but most commonly np is used as it also looks like acronym of NumPy.
### Shift + Enter for Execution

In [1]:
import numpy as np

In [2]:
print("Hello")

Hello


In [3]:
i = 1

In [4]:
i

1

In [5]:
print(1)

1


In [6]:
myarr = np.array([1,3,5,7,9])

In [7]:
myarr[0]

1

In [8]:
myarr

array([1, 3, 5, 7, 9])

In [9]:
myarr = np.array([1,3,5,7,9], np.int8) # aslo int32,int64 

In [10]:
myarr 

array([1, 3, 5, 7, 9], dtype=int8)

In [11]:
myarr = np.array([[1,3,5,7,9]])

In [12]:
myarr[0,1]

3

In [13]:
myarr.shape # No. of Rows and Columns

(1, 5)

In [14]:
myarr.dtype

dtype('int32')

In [15]:
myarr[0,1] =45

In [16]:
myarr

array([[ 1, 45,  5,  7,  9]])

## Data type objects 
### A data type object (an instance of numpy.dtype class) describes how the bytes in the fixed-size block of memory corresponding to an array item should be interpreted. 
### Dtype : Datatype or Dtype tells about the _**type of data**_ stored in the ndarray.
### By default Numpy arrays are created with float data type. And every element of Numpy array is of same data type i.e. are homogenous.

## Type of Numpy Arrays :
### (One Dimensional) arrays known as Vectors (have single row/column only).
### Multi-Dimensional arrays known as Matrices (can have multiple rows and columns).

## To access elements from Numpy Array :
### 1 – Accessing Single Dimension Array :
### For 1-D array accessing element is very easy i.e. simply write <1-D Array>[].
### 2 – Accessing Multi-Dimensional (2-D) Array :
### For 2-D array, Elements can be accessed as <2-D array>[ , ] or <2-D array>[][ ].

## 6 general mechanisms for creating arrays:
### 1. Conversion from other Python structures (i.e. lists and tuples)
### 2. Intrinsic NumPy array creation functions (e.g. arange, ones, zeros, etc.)
### 3. Replicating, joining, or mutating existing arrays
### 4. Reading arrays from disk, either from standard or custom formats
### 5. Creating arrays from raw bytes through the use of strings or buffers
### 6. Use of special library functions (e.g., random)

In [17]:
# Method 1
a1D = np.array([1, 2, 3, 4])
a2D = np.array([[1, 2], [3, 4]])
a3D = np.array([[[1, 2], [3, 4]],[[5, 6], [7, 8]]])

In [18]:
a2D

array([[1, 2],
       [3, 4]])

In [19]:
a3D

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [20]:
a2D.size

4

In [21]:
a2D.shape

(2, 2)

In [22]:
a2D.dtype

dtype('int32')

In [23]:
np.array({34,23})

array({34, 23}, dtype=object)

In [24]:
# Method 3
a = np.array([1, 2, 3, 4, 5, 6])
b = a[:2]
b += 1
print('a =', a, '; b =', b)
# In this example, we did not create a new array. 
# We created a variable, b that viewed the first 2 elements of a. 
# When we added 1 to b you would get the same result by adding 1 to a[:2].

a = [2 3 3 4 5 6] ; b = [2 3]


In [25]:
# Method 2
# numpy.zeros will create an array filled with 0 values with the specified shape. The default dtype is float64:
# numpy.ones will create an array filled with 1 values.
# numpy.arange creates arrays with regularly incrementing values.
# numpy.linspace will create arrays with a specified number of elements, and spaced equally between the specified beginning and end values. 


In [26]:
z2D = np.zeros((2, 3))

In [27]:
z2D

array([[0., 0., 0.],
       [0., 0., 0.]])

In [28]:
z2D.dtype

dtype('float64')

In [29]:
z2D.shape

(2, 3)

In [30]:
np.zeros((2, 3, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [31]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
np.arange(2, 10, dtype=float)

array([2., 3., 4., 5., 6., 7., 8., 9.])

In [33]:
np.arange(2, 3, 0.1)

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

In [34]:
np.linspace(1., 4., 6)

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

In [35]:
np.empty((4,6)) # Return a new array without initializing entries.

array([[4.67296746e-307, 1.69121096e-306, 1.69118787e-306,
        1.33511018e-306, 1.33511969e-306, 6.23037996e-307],
       [1.60218627e-306, 6.23061763e-307, 6.23058028e-307,
        1.11260348e-306, 1.16825884e-307, 8.90060780e-307],
       [8.90029545e-307, 8.90029545e-307, 1.24611470e-306,
        1.11261027e-306, 1.02360731e-306, 1.05700515e-307],
       [1.11261774e-306, 1.29060871e-306, 8.34424766e-308,
        8.34445138e-308, 1.37959129e-306, 1.02360528e-306]])

In [36]:
np.empty_like(z2D) # Return a new array with the same shape and type as a given array.


array([[1. , 1.6, 2.2],
       [2.8, 3.4, 4. ]])

In [37]:
np.identity(3) # Return the identity array which is a square array with ones on the main diagonal.

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [38]:
a = np.arange(6)

In [39]:
a

array([0, 1, 2, 3, 4, 5])

In [40]:
a.reshape((3, 2)) # Gives a new shape to an array without changing its data.

array([[0, 1],
       [2, 3],
       [4, 5]])

In [41]:
a # Original not Changed

array([0, 1, 2, 3, 4, 5])

In [42]:
a = a.reshape((3, 2)) # Orginal Changed

In [43]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [44]:
a = a.ravel() # Return a contiguous flattened array.

In [45]:
a

array([0, 1, 2, 3, 4, 5])

## Numpy Axis
### Another term for an array dimension. 
### Axes are numbered left to right; axis 0 is the first element in the shape tuple.
### In a two-dimensional vector, the elements of axis 0 are rows and the elements of axis 1 are columns.
### 1D -> [1,2,3] 1 Axis
### 2D -> [[0, 1], [2, 3], [4, 5]] 2Axis [Axis 0(Row), Axis 1(Coulmn)]

In [46]:
x = [[ 1, 2, 3], [ 4, 5, 6], [ 7, 0, 1]]

In [47]:
arrX = np.array(x)

In [48]:
arrX

array([[1, 2, 3],
       [4, 5, 6],
       [7, 0, 1]])

In [49]:
arrX.sum(axis=0) # Sum of Individual Rows

array([12,  7, 10])

In [50]:
arrX.sum(axis=1) # Sum of Individual Columns

array([ 6, 15,  8])

In [51]:
arrX.T # Transpose Array (Rows , Columns Interchange)

array([[1, 4, 7],
       [2, 5, 0],
       [3, 6, 1]])

In [52]:
for i in arrX.flat: # A 1-D iterator over the array.
    print(i)

1
2
3
4
5
6
7
0
1


In [53]:
arrX.ndim # No. of Dimensions

2

In [54]:
arrX.size # No. of elements in array

9

In [55]:
arrX.nbytes # Total bytes consumed by the elements of the array.

36

In [56]:
a = np.arange(6).reshape(2,3) + 10

In [57]:
a

array([[10, 11, 12],
       [13, 14, 15]])

In [58]:
np.argmax(a) # Returns the indices of the maximum values along an axis and In 2D first change into 1D then find and return index (Axis=0,1)

5

In [59]:
np.argmin(a) # Returns the indices of the minimum values along an axis and In 2D first change into 1D then find and return index (Axis=0,1)

0

In [60]:
np.argsort(a) # Returns the indices that would sort an array and In 2D first change into 1D then find and return index (Axis=0,1)

array([[0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [61]:
arrX

array([[1, 2, 3],
       [4, 5, 6],
       [7, 0, 1]])

In [62]:
arrY = np.array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [63]:
arrY

array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [64]:
arrX + arrY # Addition possible but not in list

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  1,  1]])

In [65]:
arrX * arrY # Element wise

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  0,  0]])

In [66]:
np.sqrt(arrX) # Square Root element wise

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 0.        , 1.        ]])

In [67]:
arrX.sum() # Sum of all elements

29

In [68]:
arrX.max() # Max of all elements

7

In [69]:
arrX.min() # Min of all elements

0

In [70]:
np.where(arrX>5) # Finds element

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [71]:
arrX

array([[1, 2, 3],
       [4, 5, 6],
       [7, 0, 1]])

In [72]:
type(np.where(arrX>5)) # To check type

tuple

In [73]:
np.count_nonzero(arrX) # Counts non 0 values

8

In [74]:
np.nonzero(arrX) # Indices of non 0 elements

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 2], dtype=int64))

In [75]:
arrX[1,2] = 0

In [76]:
np.nonzero(arrX)

(array([0, 0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 0, 2], dtype=int64))

In [77]:
import sys

In [78]:
py_arr = [0,4,55,2]

In [79]:
np_arr = np.array(py_arr)

In [80]:
sys.getsizeof(1) * len(py_arr)

112

In [81]:
np_arr.itemsize * np_arr.size

16